let productsArray = [
  {
    id: 0,
    name: 'Jeans',
    price: 29.99,
    instock: 100,
    description: 'Fancy description.',
  },
  {
    id: 1,
    name: 'T-shirt',
    price: 24.99,
    instock: 43,
    description: 'Fancy description.',
  },
  {
    id: 2,
    name: 'Hat',
    price: 19.99,
    instock: 10,
    description: 'Fancy description.',
    imgSrc: './img/t3.png',
  },
  {
    id: 3,
    name: 'Socks',
    price: 25.99,
    instock: 5,
    description: 'Fancy shirt description.',
  },
  {
    id: 4,
    name: 'Tie',
    price: 29.99,
    instock: 4,
    description: 'Fancy description.',
  },
  {
    id: 5,
    name: 'Button Up',
    price: 39.99,
    instock: 40,
    description: 'Fancy description.',
  },
];
